# fly.toml app configuration file generated for leitorbarras on 2024-10-27T23:01:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leitorbarras'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
