services:
  - type: web
    name: leitorbarras
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libzbar0 && pip install -r requirements.txt
    startCommand: python server.py
